# Archivo: alacritty.toml.template
[colors.primary]
background = "#2d353b"
foreground = "#d3c6aa"

[colors.selection]
text = "#475258"
background = "#a7c080"

[window] #1.0 es opaco, 0.0 es invisible.
opacity = 0.90
# Importnte: esto ayuda a que el fondo no distraiga tanto
blur = true

#Margen del texto
# [window.padding]
# x = 10
# y = 10
